apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-app-deployment
  labels:
    app: will
spec:
  replicas: 1
  selector:
    matchLabels:
      app: will
  template:
    metadata:
      labels:
        app: will
    spec:
      containers:
      - name: will
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
#        livenessProbe:              #Prevent the app from dying by restarting it if it dies. This is not explicitly demanded in project description but I do it to prevent failures.
#          tcpSocket:
#            port: 8888
#          initialDelaySeconds: 10
#          periodSeconds: 10
