Vagrant.configure("2") do |config|
	config.vm.box = "generic/alpine312"
        config.vm.define "agloriosS" do |master|
	  master.vm.network "private_network", ip: "192.168.56.110"
	  master.vm.synced_folder "./confs", "/vagrant", type: "virtualbox"
	  master.vm.hostname = "agloriosS"
	  master.vm.provider "virtualbox" do |vb|
		  vb.memory = "2048"
		  vb.cpus = "1"
		  vb.name = "agloriosS"
	  end
          master.vm.provision "shell", path: "./scripts/setup.sh"
      end
end
