Vagrant.configure("2") do |config|

  config.vm.define "agloriosS" do |master|
    master.vm.box = "generic/alpine312"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.hostname = "agloriosS"
	master.vm.synced_folder "./confs", "/vagrant", type:"virtualbox"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
	  vb.cpus = "1"
	  vb.name = "agloriosS"
	end

    master.vm.provision "shell", inline: <<-SHELL
	  curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-iface eth1" sh -
	  sleep 10
	  sudo chmod 644 /etc/rancher/k3s/k3s.yaml
	  NODE_TOKEN="/var/lib/rancher/k3s/server/node-token"
      while [ ! -e ${NODE_TOKEN} ]
      do
          sleep 2
      done
      sudo cat ${NODE_TOKEN}
      sudo cp ${NODE_TOKEN} /vagrant/
      KUBE_CONFIG="/etc/rancher/k3s/k3s.yaml"
      sudo cp ${KUBE_CONFIG} /vagrant/
    SHELL
  end
   
  config.vm.define "agloriosSW" do |node1|
    node1.vm.box = "generic/alpine312"
    node1.vm.hostname = "agloriosSW"
	node1.vm.synced_folder "./confs", "/vagrant", type:"virtualbox"
	node1.vm.network "private_network", ip: "192.168.56.111"
    node1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
      vb.name = "agloriosSW"
	end

    node1.vm.provision "shell", inline: <<-SHELL
	  curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-iface eth1" K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$(sudo cat /vagrant/node-token) sh -
	  sleep 10
    SHELL
  end

end
